### ISSUE TITLE
New to this and getting an Compilation error

### ISSUE THREAD

**Issue by CCooper1971** [kevinl95/KeychainSkimmerScanner#1]
I followed the instruction and getting an error. see below. 

C:\Users\XXXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:10:10: fatal error: M5CoreInk.h: No such file or directory
 #include "M5CoreInk.h"
          ^~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: M5CoreInk.h: No such file or directory

I XXXX out my user name . Sorry I am really new at this.

**Comment by CCooper1971** [comment]
After some googling I got passed the 1st error now getting.

tcp/h264://192.168.1.21:8554
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:21:17: error: redefinition of 'BluetoothSerial SerialBT'
 BluetoothSerial SerialBT;
                 ^~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:21:17: note: 'BluetoothSerial SerialBT' previously declared here
 BluetoothSerial SerialBT;
                 ^~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:25:6: error: redefinition of 'void btAdvertisedDeviceFound(BTAdvertisedDevice*)'
 void btAdvertisedDeviceFound(BTAdvertisedDevice *pDevice) {
      ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:25:6: note: 'void btAdvertisedDeviceFound(BTAdvertisedDevice*)' previously defined here
 void btAdvertisedDeviceFound(BTAdvertisedDevice *pDevice) {
      ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:29:25: error: redefinition of 'Ink_Sprite InkPageSprite'
 Ink_Sprite InkPageSprite(&M5.M5Ink);
                         ^
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:29:12: note: 'Ink_Sprite InkPageSprite' previously declared here
 Ink_Sprite InkPageSprite(&M5.M5Ink);
            ^~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:35:6: error: redefinition of 'char StrContains(char*, char*)'
 char StrContains(char *str, char *sfind)
      ^~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:35:6: note: 'char StrContains(char*, char*)' previously defined here
 char StrContains(char *str, char *sfind)
      ^~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:63:6: error: redefinition of 'void Scan()'
 void Scan() {
      ^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:63:6: note: 'void Scan()' previously defined here
 void Scan() {
      ^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:111:6: error: redefinition of 'void Reset()'
 void Reset() {
      ^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:111:6: note: 'void Reset()' previously defined here
 void Reset() {
      ^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:123:6: error: redefinition of 'void setup()'
 void setup() {
      ^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:123:6: note: 'void setup()' previously defined here
 void setup() {
      ^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:141:6: error: redefinition of 'void loop()'
 void loop() {
      ^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:141:6: note: 'void loop()' previously defined here
 void loop() {
      ^~~~

exit status 1

Compilation error: redefinition of 'BluetoothSerial SerialBT'

**Comment by johnwargo** [comment]
The instructions have you installing the M5Stack libraries, but the `M5CoreInk` library you need is a separate download. That's the source of the first error. 
![image](https://github.com/user-attachments/assets/b6d28e49-88b7-4ed7-884d-0e7e22e8463c)

**Comment by johnwargo** [comment]
you should close the issue after you resolved it then create a new one for the second issue.

**Comment by CCooper1971** [comment]
After some googling I got passed the error

**Comment by CCooper1971** [comment]
After some googling I got passed the error

**Comment by CCooper1971** [comment]
After some googling I got passed the error
