### ISSUE TITLE
Compilation error: redefinition of 'BluetoothSerial SerialBT'

### ISSUE THREAD

**Issue by CCooper1971** [kevinl95/KeychainSkimmerScanner#2]
Hello getting this error far as I can the BluetoothSerial library is installed

tcp/h264://192.168.1.21:8554
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:21:17: error: redefinition of 'BluetoothSerial SerialBT'
BluetoothSerial SerialBT;
^~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:21:17: note: 'BluetoothSerial SerialBT' previously declared here
BluetoothSerial SerialBT;
^~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:25:6: error: redefinition of 'void btAdvertisedDeviceFound(BTAdvertisedDevice*)'
void btAdvertisedDeviceFound(BTAdvertisedDevice pDevice) {
^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:25:6: note: 'void btAdvertisedDeviceFound(BTAdvertisedDevice)' previously defined here
void btAdvertisedDeviceFound(BTAdvertisedDevice pDevice) {
^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:29:25: error: redefinition of 'Ink_Sprite InkPageSprite'
Ink_Sprite InkPageSprite(&M5.M5Ink);
^
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:29:12: note: 'Ink_Sprite InkPageSprite' previously declared here
Ink_Sprite InkPageSprite(&M5.M5Ink);
^~~~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:35:6: error: redefinition of 'char StrContains(char, char*)'
char StrContains(char str, char sfind)
^~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:35:6: note: 'char StrContains(char, char)' previously defined here
char StrContains(char *str, char *sfind)
^~~~~~~~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:63:6: error: redefinition of 'void Scan()'
void Scan() {
^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:63:6: note: 'void Scan()' previously defined here
void Scan() {
^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:111:6: error: redefinition of 'void Reset()'
void Reset() {
^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:111:6: note: 'void Reset()' previously defined here
void Reset() {
^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:123:6: error: redefinition of 'void setup()'
void setup() {
^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:123:6: note: 'void setup()' previously defined here
void setup() {
^~~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main1.ino:141:6: error: redefinition of 'void loop()'
void loop() {
^~~~
C:\Users\XXXX\Downloads\KeychainSkimmerScanner-main\KeychainSkimmerScanner-main\main\main.ino:141:6: note: 'void loop()' previously defined here
void loop() {
^~~~

exit status 1

Compilation error: redefinition of 'BluetoothSerial SerialBT'

**Comment by CCooper1971** [comment]
Well I got it to install. I slowed the the upload speed (115200) and enabled erase all flash before upload. It installed and seems to run but it will not always show Bluetooth devices near it so not sure how well it works.

**Comment by kevinl95** [comment]
Hi @CCooper1971 ,

Sorry for the delay in writing back to you. Have you had any more success with Bluetooth scanning? If possible, check if the devices you are running the scan near are Bluetooth Classic and not Bluetooth Low Energy devices, as the latter are not enumerated by the code here. You can also adjust the variable BT_DISCOVER_TIME at the top of the .ino file from 10 seconds to a large number and see if that improves your results.
